sudo: false
language: cpp
os: linux
compiler: gcc-4.9
addons:
    apt:
        sources: ['ubuntu-toolchain-r-test']
        packages: ['g++-4.9', 'zlib1g-dev', 'libbz2-dev']
    install: export CXX="g++-4.9" CC="gcc-4.9"
script: ./test/run_tests.sh
